controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

profile:
    path: /profile
    controller: App\Controller\ProfileController::index
   

settings:
    path: /settings
    controller: App\Controller\SettingsController::index
  
